"""initial schema

Revision ID: 0f21d00d4152
Revises:
Create Date: 2026-09-11 10:35:16.152478

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0f21d00d4152"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "suppliers",
        sa.Column("supplier_id", sa.String(length=64), nullable=False),
        sa.Column("legal_name", sa.String(length=255), nullable=False),
        sa.Column("trading_name", sa.String(length=255), nullable=False),
        sa.Column("group", sa.String(length=255), nullable=False),
        sa.Column("nib", sa.String(length=32), nullable=False),
        sa.Column("npwp", sa.String(length=32), nullable=False),
        sa.Column("hgu_number", sa.String(length=64), nullable=True),
        sa.Column("pbp_number", sa.String(length=64), nullable=True),
        sa.Column("permit_status", sa.String(length=16), nullable=False),
        sa.Column("concession_area_ha", sa.Float(), nullable=False),
        sa.Column("province", sa.String(length=64), nullable=False),
        sa.Column("kabupaten", sa.String(length=64), nullable=False),
        sa.Column(
            "beneficial_owners",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "certifications",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "sanctions",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("synthetic", sa.Boolean(), nullable=False),
        sa.Column("disclosure", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("supplier_id", name=op.f("pk_suppliers")),
    )
    op.create_table(
        "parcels",
        sa.Column("polygon_id", sa.String(length=64), nullable=False),
        sa.Column("supplier_id", sa.String(length=64), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("region", sa.String(length=128), nullable=False),
        sa.Column("province", sa.String(length=64), nullable=False),
        sa.Column("area_ha", sa.Float(), nullable=False),
        sa.Column("centroid_lat", sa.Float(), nullable=False),
        sa.Column("centroid_lon", sa.Float(), nullable=False),
        sa.Column(
            "geometry",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("archetype", sa.String(length=16), nullable=False),
        sa.Column("scenario", sa.String(length=32), nullable=True),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.supplier_id"],
            name=op.f("fk_parcels_supplier_id_suppliers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("polygon_id", name=op.f("pk_parcels")),
    )
    op.create_index(op.f("ix_parcels_supplier_id"), "parcels", ["supplier_id"], unique=False)
    op.create_table(
        "runs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("parent_run_id", sa.String(length=64), nullable=True),
        sa.Column("record_id", sa.String(length=64), nullable=True),
        sa.Column("supplier_id", sa.String(length=64), nullable=True),
        sa.Column("polygon_id", sa.String(length=64), nullable=True),
        sa.Column(
            "state",
            sa.Enum(
                "queued",
                "running",
                "needs_more_data",
                "awaiting_review",
                "complete",
                "failed",
                name="runstate",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("model", sa.String(length=32), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "disclosures",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "metrics",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "verification",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("elapsed_seconds", sa.Float(), nullable=True),
        sa.Column("review_decision", sa.String(length=16), nullable=True),
        sa.Column("review_reviewer", sa.String(length=128), nullable=True),
        sa.Column("review_note", sa.Text(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_run_id"], ["runs.id"], name=op.f("fk_runs_parent_run_id_runs"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["polygon_id"], ["parcels.polygon_id"], name=op.f("fk_runs_polygon_id_parcels")
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"], ["suppliers.supplier_id"], name=op.f("fk_runs_supplier_id_suppliers")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_runs")),
    )
    op.create_index(op.f("ix_runs_kind"), "runs", ["kind"], unique=False)
    op.create_index(op.f("ix_runs_parent_run_id"), "runs", ["parent_run_id"], unique=False)
    op.create_index(op.f("ix_runs_record_id"), "runs", ["record_id"], unique=False)
    op.create_table(
        "dds_documents",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column(
            "document",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("xml", sa.Text(), nullable=False),
        sa.Column("released", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_dds_documents_run_id_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dds_documents")),
        sa.UniqueConstraint("run_id", name="uq_dds_documents_run_id"),
    )
    op.create_index(op.f("ix_dds_documents_run_id"), "dds_documents", ["run_id"], unique=False)
    op.create_table(
        "evidence",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("evidence_id", sa.String(length=96), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("claim", sa.String(length=128), nullable=False),
        sa.Column(
            "value",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("unit", sa.String(length=32), nullable=True),
        sa.Column("source", sa.String(length=48), nullable=False),
        sa.Column(
            "artifact",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cached", sa.Boolean(), nullable=False),
        sa.Column("synthetic", sa.Boolean(), nullable=False),
        sa.Column("disclosure", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_evidence_run_id_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence")),
        sa.UniqueConstraint("run_id", "evidence_id", name="uq_evidence_run_id_evidence_id"),
    )
    op.create_index(op.f("ix_evidence_run_id"), "evidence", ["run_id"], unique=False)
    op.create_table(
        "run_steps",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("step_id", sa.String(length=16), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_run_steps_run_id_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run_steps")),
        sa.UniqueConstraint("run_id", "step_id", name="uq_run_steps_run_id_step_id"),
    )
    op.create_index(op.f("ix_run_steps_run_id"), "run_steps", ["run_id"], unique=False)
    op.create_table(
        "verdicts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("record_id", sa.String(length=64), nullable=False),
        sa.Column("supplier_id", sa.String(length=64), nullable=False),
        sa.Column("polygon_id", sa.String(length=64), nullable=False),
        sa.Column("rubric_version", sa.String(length=32), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column(
            "verdict",
            sa.Enum("compliant", "high_risk", "ambiguous", name="verdict", native_enum=False, length=24),
            nullable=False,
        ),
        sa.Column(
            "risk_level",
            sa.Enum("negligible", "non_negligible", name="risklevel", native_enum=False, length=24),
            nullable=False,
        ),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column(
            "findings",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "citations",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "disclosures",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "data_gaps",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("expected_archetype", sa.String(length=16), nullable=False),
        sa.Column("expected_signal", sa.String(length=16), nullable=True),
        sa.Column("expected_ambiguity", sa.String(length=32), nullable=True),
        sa.Column("pending", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_verdicts_run_id_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_verdicts")),
        sa.UniqueConstraint("run_id", name="uq_verdicts_run_id"),
    )
    op.create_index(op.f("ix_verdicts_run_id"), "verdicts", ["run_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_verdicts_run_id"), table_name="verdicts")
    op.drop_table("verdicts")
    op.drop_index(op.f("ix_run_steps_run_id"), table_name="run_steps")
    op.drop_table("run_steps")
    op.drop_index(op.f("ix_evidence_run_id"), table_name="evidence")
    op.drop_table("evidence")
    op.drop_index(op.f("ix_dds_documents_run_id"), table_name="dds_documents")
    op.drop_table("dds_documents")
    op.drop_index(op.f("ix_runs_record_id"), table_name="runs")
    op.drop_index(op.f("ix_runs_parent_run_id"), table_name="runs")
    op.drop_index(op.f("ix_runs_kind"), table_name="runs")
    op.drop_table("runs")
    op.drop_index(op.f("ix_parcels_supplier_id"), table_name="parcels")
    op.drop_table("parcels")
    op.drop_table("suppliers")
    # ### end Alembic commands ###
