"""sap actions audit

Revision ID: fa63e54f2542
Revises: 0f21d00d4152
Create Date: 2026-09-11 14:00:27.508268

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fa63e54f2542"
down_revision: str | Sequence[str] | None = "0f21d00d4152"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sap_actions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("supplier_id", sa.String(length=64), nullable=False),
        sa.Column("vendor_id", sa.String(length=64), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("purchasing_block", sa.Boolean(), nullable=False),
        sa.Column("real", sa.Boolean(), nullable=False),
        sa.Column("external_reference", sa.String(length=255), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("performed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_sap_actions_run_id_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sap_actions")),
    )
    op.create_index(op.f("ix_sap_actions_run_id"), "sap_actions", ["run_id"], unique=False)
    op.create_index(op.f("ix_sap_actions_supplier_id"), "sap_actions", ["supplier_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sap_actions_supplier_id"), table_name="sap_actions")
    op.drop_index(op.f("ix_sap_actions_run_id"), table_name="sap_actions")
    op.drop_table("sap_actions")
    # ### end Alembic commands ###
